theme: minima

title: Golden State Digital Network
description: > 
  The GSDN supports peer-to-peer collaboration between organizations
  that are currently providing free or low-cost services to California
  libraries, archives, museums and other cultural heritage institutions,
  to support the lifecycle management and broad public access to
  unique digital collections -- leveraging existing statewide and
  national discovery systems. Through participation in the GSDN,
  service organizations can more effectively share resources,
  coordinate workflows, and forge new inter-institutional partnerships
  -- thereby augmenting each organization's individual capacities.


author: California Digital Library
email: oacops@cdlib.org
# social links
# twitter_username: jekyllrb
# github_username:  jekyll
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - affiliates.md
 - contributors.md 

plugins:
 - jekyll-feed
 - jekyll-seo-tag
